@BASE_URL = http://localhost:8888

### regis doc
post {{BASE_URL}}/auth/register/doctor
Content-Type: application/json

{
  "username": "jojo380",
  "password": "123456",
  "specialization": "Cardiologist"
}


### regis user
POST {{BASE_URL}}/auth/register/user
Content-Type: application/json

{
  "username": "gogo2",
  "password": "123456"
}

### login doc
post {{BASE_URL}}/auth/login/doctor
Content-Type: application/json

{
  "username": "jojo380",
  "password": "123456"
}